// Copyright 2026 Sam Lock
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pollen/admission/v1/admission.proto

package admissionv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapPeer struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	PeerPub []byte                 `protobuf:"bytes,1,opt,name=peer_pub,json=peerPub,proto3" json:"peer_pub,omitempty"`
	Addrs   []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// host:port of this peer's TLS+mTLS control listener (control-tls).
	// Empty if the peer has no wire listener. Joiners writing a ctx may use
	// this as the wire fallback so the CLI keeps working when the local
	// daemon is down. No scheme: callers prepend `pln://` for display.
	WireEndpoint  string `protobuf:"bytes,3,opt,name=wire_endpoint,json=wireEndpoint,proto3" json:"wire_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapPeer) Reset() {
	*x = BootstrapPeer{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapPeer) ProtoMessage() {}

func (x *BootstrapPeer) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapPeer.ProtoReflect.Descriptor instead.
func (*BootstrapPeer) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapPeer) GetPeerPub() []byte {
	if x != nil {
		return x.PeerPub
	}
	return nil
}

func (x *BootstrapPeer) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *BootstrapPeer) GetWireEndpoint() string {
	if x != nil {
		return x.WireEndpoint
	}
	return ""
}

type AccessTokenClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceID            `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	IssuerPub     []byte                 `protobuf:"bytes,2,opt,name=issuer_pub,json=issuerPub,proto3" json:"issuer_pub,omitempty"`
	IssuedAtUnix  int64                  `protobuf:"varint,3,opt,name=issued_at_unix,json=issuedAtUnix,proto3" json:"issued_at_unix,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,4,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenClaims) Reset() {
	*x = AccessTokenClaims{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenClaims) ProtoMessage() {}

func (x *AccessTokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenClaims.ProtoReflect.Descriptor instead.
func (*AccessTokenClaims) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenClaims) GetResource() *ResourceID {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AccessTokenClaims) GetIssuerPub() []byte {
	if x != nil {
		return x.IssuerPub
	}
	return nil
}

func (x *AccessTokenClaims) GetIssuedAtUnix() int64 {
	if x != nil {
		return x.IssuedAtUnix
	}
	return 0
}

func (x *AccessTokenClaims) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *AccessTokenClaims     `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{2}
}

func (x *AccessToken) GetClaims() *AccessTokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *AccessToken) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ResourceID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ResourceID_Seed
	//	*ResourceID_Blob
	//	*ResourceID_Static
	//	*ResourceID_Service
	Body          isResourceID_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceID) Reset() {
	*x = ResourceID{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceID) ProtoMessage() {}

func (x *ResourceID) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceID.ProtoReflect.Descriptor instead.
func (*ResourceID) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceID) GetBody() isResourceID_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResourceID) GetSeed() *SeedID {
	if x != nil {
		if x, ok := x.Body.(*ResourceID_Seed); ok {
			return x.Seed
		}
	}
	return nil
}

func (x *ResourceID) GetBlob() *BlobID {
	if x != nil {
		if x, ok := x.Body.(*ResourceID_Blob); ok {
			return x.Blob
		}
	}
	return nil
}

func (x *ResourceID) GetStatic() *StaticID {
	if x != nil {
		if x, ok := x.Body.(*ResourceID_Static); ok {
			return x.Static
		}
	}
	return nil
}

func (x *ResourceID) GetService() *ServiceID {
	if x != nil {
		if x, ok := x.Body.(*ResourceID_Service); ok {
			return x.Service
		}
	}
	return nil
}

type isResourceID_Body interface {
	isResourceID_Body()
}

type ResourceID_Seed struct {
	Seed *SeedID `protobuf:"bytes,1,opt,name=seed,proto3,oneof"`
}

type ResourceID_Blob struct {
	Blob *BlobID `protobuf:"bytes,2,opt,name=blob,proto3,oneof"`
}

type ResourceID_Static struct {
	Static *StaticID `protobuf:"bytes,3,opt,name=static,proto3,oneof"`
}

type ResourceID_Service struct {
	Service *ServiceID `protobuf:"bytes,4,opt,name=service,proto3,oneof"`
}

func (*ResourceID_Seed) isResourceID_Body() {}

func (*ResourceID_Blob) isResourceID_Body() {}

func (*ResourceID_Static) isResourceID_Body() {}

func (*ResourceID_Service) isResourceID_Body() {}

type SeedID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedID) Reset() {
	*x = SeedID{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedID) ProtoMessage() {}

func (x *SeedID) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedID.ProtoReflect.Descriptor instead.
func (*SeedID) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{4}
}

func (x *SeedID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeedID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type BlobID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobID) Reset() {
	*x = BlobID{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobID) ProtoMessage() {}

func (x *BlobID) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobID.ProtoReflect.Descriptor instead.
func (*BlobID) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{5}
}

func (x *BlobID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlobID) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type StaticID struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ManifestDigest []byte                 `protobuf:"bytes,2,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StaticID) Reset() {
	*x = StaticID{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticID) ProtoMessage() {}

func (x *StaticID) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticID.ProtoReflect.Descriptor instead.
func (*StaticID) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{6}
}

func (x *StaticID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaticID) GetManifestDigest() []byte {
	if x != nil {
		return x.ManifestDigest
	}
	return nil
}

type ServiceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceID) Reset() {
	*x = ServiceID{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceID) ProtoMessage() {}

func (x *ServiceID) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceID.ProtoReflect.Descriptor instead.
func (*ServiceID) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Predicate struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Inline *InlinePredicate       `protobuf:"bytes,1,opt,name=inline,proto3" json:"inline,omitempty"`
	// public, when true, permits anonymous callers (no grant) and
	// short-circuits attribute clause evaluation.
	Public        bool `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{8}
}

func (x *Predicate) GetInline() *InlinePredicate {
	if x != nil {
		return x.Inline
	}
	return nil
}

func (x *Predicate) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

type InlinePredicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clauses       []*Clause              `protobuf:"bytes,1,rep,name=clauses,proto3" json:"clauses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlinePredicate) Reset() {
	*x = InlinePredicate{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlinePredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlinePredicate) ProtoMessage() {}

func (x *InlinePredicate) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlinePredicate.ProtoReflect.Descriptor instead.
func (*InlinePredicate) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{9}
}

func (x *InlinePredicate) GetClauses() []*Clause {
	if x != nil {
		return x.Clauses
	}
	return nil
}

type Clause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Equals        string                 `protobuf:"bytes,2,opt,name=equals,proto3" json:"equals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clause) Reset() {
	*x = Clause{}
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clause) ProtoMessage() {}

func (x *Clause) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_admission_v1_admission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clause.ProtoReflect.Descriptor instead.
func (*Clause) Descriptor() ([]byte, []int) {
	return file_pollen_admission_v1_admission_proto_rawDescGZIP(), []int{10}
}

func (x *Clause) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Clause) GetEquals() string {
	if x != nil {
		return x.Equals
	}
	return ""
}

var File_pollen_admission_v1_admission_proto protoreflect.FileDescriptor

const file_pollen_admission_v1_admission_proto_rawDesc = "" +
	"\n" +
	"#pollen/admission/v1/admission.proto\x12\x13pollen.admission.v1\x1a\x1bbuf/validate/validate.proto\"~\n" +
	"\rBootstrapPeer\x12\"\n" +
	"\bpeer_pub\x18\x01 \x01(\fB\a\xbaH\x04z\x02h R\apeerPub\x12$\n" +
	"\x05addrs\x18\x02 \x03(\tB\x0e\xbaH\v\x92\x01\b\b\x01\"\x04r\x02\x10\x01R\x05addrs\x12#\n" +
	"\rwire_endpoint\x18\x03 \x01(\tR\fwireEndpoint\"\xce\x01\n" +
	"\x11AccessTokenClaims\x12C\n" +
	"\bresource\x18\x01 \x01(\v2\x1f.pollen.admission.v1.ResourceIDB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12&\n" +
	"\n" +
	"issuer_pub\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\tissuerPub\x12$\n" +
	"\x0eissued_at_unix\x18\x03 \x01(\x03R\fissuedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x04 \x01(\x03R\rexpiresAtUnix\"|\n" +
	"\vAccessToken\x12F\n" +
	"\x06claims\x18\x01 \x01(\v2&.pollen.admission.v1.AccessTokenClaimsB\x06\xbaH\x03\xc8\x01\x01R\x06claims\x12%\n" +
	"\tsignature\x18\x02 \x01(\fB\a\xbaH\x04z\x02h@R\tsignature\"\xef\x01\n" +
	"\n" +
	"ResourceID\x121\n" +
	"\x04seed\x18\x01 \x01(\v2\x1b.pollen.admission.v1.SeedIDH\x00R\x04seed\x121\n" +
	"\x04blob\x18\x02 \x01(\v2\x1b.pollen.admission.v1.BlobIDH\x00R\x04blob\x127\n" +
	"\x06static\x18\x03 \x01(\v2\x1d.pollen.admission.v1.StaticIDH\x00R\x06static\x12:\n" +
	"\aservice\x18\x04 \x01(\v2\x1e.pollen.admission.v1.ServiceIDH\x00R\aserviceB\x06\n" +
	"\x04body\"E\n" +
	"\x06SeedID\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x12\x1b\n" +
	"\x04hash\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\x04hash\"G\n" +
	"\x06BlobID\x12\x1c\n" +
	"\x04name\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\x04name\x12\x1f\n" +
	"\x06digest\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\x06digest\"\\\n" +
	"\bStaticID\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\x120\n" +
	"\x0fmanifest_digest\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\x0emanifestDigest\"+\n" +
	"\tServiceID\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x04name\"a\n" +
	"\tPredicate\x12<\n" +
	"\x06inline\x18\x01 \x01(\v2$.pollen.admission.v1.InlinePredicateR\x06inline\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public\"H\n" +
	"\x0fInlinePredicate\x125\n" +
	"\aclauses\x18\x01 \x03(\v2\x1b.pollen.admission.v1.ClauseR\aclauses\"E\n" +
	"\x06Clause\x12\x19\n" +
	"\x03key\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12\x16\n" +
	"\x06equals\x18\x02 \x01(\tR\x06equalsJ\x04\b\x03\x10\x04R\x02inBHZFgithub.com/sambigeara/pollen/api/genpb/pollen/admission/v1;admissionv1b\x06proto3"

var (
	file_pollen_admission_v1_admission_proto_rawDescOnce sync.Once
	file_pollen_admission_v1_admission_proto_rawDescData []byte
)

func file_pollen_admission_v1_admission_proto_rawDescGZIP() []byte {
	file_pollen_admission_v1_admission_proto_rawDescOnce.Do(func() {
		file_pollen_admission_v1_admission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pollen_admission_v1_admission_proto_rawDesc), len(file_pollen_admission_v1_admission_proto_rawDesc)))
	})
	return file_pollen_admission_v1_admission_proto_rawDescData
}

var file_pollen_admission_v1_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pollen_admission_v1_admission_proto_goTypes = []any{
	(*BootstrapPeer)(nil),     // 0: pollen.admission.v1.BootstrapPeer
	(*AccessTokenClaims)(nil), // 1: pollen.admission.v1.AccessTokenClaims
	(*AccessToken)(nil),       // 2: pollen.admission.v1.AccessToken
	(*ResourceID)(nil),        // 3: pollen.admission.v1.ResourceID
	(*SeedID)(nil),            // 4: pollen.admission.v1.SeedID
	(*BlobID)(nil),            // 5: pollen.admission.v1.BlobID
	(*StaticID)(nil),          // 6: pollen.admission.v1.StaticID
	(*ServiceID)(nil),         // 7: pollen.admission.v1.ServiceID
	(*Predicate)(nil),         // 8: pollen.admission.v1.Predicate
	(*InlinePredicate)(nil),   // 9: pollen.admission.v1.InlinePredicate
	(*Clause)(nil),            // 10: pollen.admission.v1.Clause
}
var file_pollen_admission_v1_admission_proto_depIdxs = []int32{
	3,  // 0: pollen.admission.v1.AccessTokenClaims.resource:type_name -> pollen.admission.v1.ResourceID
	1,  // 1: pollen.admission.v1.AccessToken.claims:type_name -> pollen.admission.v1.AccessTokenClaims
	4,  // 2: pollen.admission.v1.ResourceID.seed:type_name -> pollen.admission.v1.SeedID
	5,  // 3: pollen.admission.v1.ResourceID.blob:type_name -> pollen.admission.v1.BlobID
	6,  // 4: pollen.admission.v1.ResourceID.static:type_name -> pollen.admission.v1.StaticID
	7,  // 5: pollen.admission.v1.ResourceID.service:type_name -> pollen.admission.v1.ServiceID
	9,  // 6: pollen.admission.v1.Predicate.inline:type_name -> pollen.admission.v1.InlinePredicate
	10, // 7: pollen.admission.v1.InlinePredicate.clauses:type_name -> pollen.admission.v1.Clause
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pollen_admission_v1_admission_proto_init() }
func file_pollen_admission_v1_admission_proto_init() {
	if File_pollen_admission_v1_admission_proto != nil {
		return
	}
	file_pollen_admission_v1_admission_proto_msgTypes[3].OneofWrappers = []any{
		(*ResourceID_Seed)(nil),
		(*ResourceID_Blob)(nil),
		(*ResourceID_Static)(nil),
		(*ResourceID_Service)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pollen_admission_v1_admission_proto_rawDesc), len(file_pollen_admission_v1_admission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pollen_admission_v1_admission_proto_goTypes,
		DependencyIndexes: file_pollen_admission_v1_admission_proto_depIdxs,
		MessageInfos:      file_pollen_admission_v1_admission_proto_msgTypes,
	}.Build()
	File_pollen_admission_v1_admission_proto = out.File
	file_pollen_admission_v1_admission_proto_goTypes = nil
	file_pollen_admission_v1_admission_proto_depIdxs = nil
}
