// Copyright 2026 Sam Lock
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: pollen/control/v1/control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlService_Shutdown_FullMethodName          = "/pollen.control.v1.ControlService/Shutdown"
	ControlService_GetBootstrapInfo_FullMethodName  = "/pollen.control.v1.ControlService/GetBootstrapInfo"
	ControlService_GetStatus_FullMethodName         = "/pollen.control.v1.ControlService/GetStatus"
	ControlService_GetMetrics_FullMethodName        = "/pollen.control.v1.ControlService/GetMetrics"
	ControlService_RegisterService_FullMethodName   = "/pollen.control.v1.ControlService/RegisterService"
	ControlService_UnregisterService_FullMethodName = "/pollen.control.v1.ControlService/UnregisterService"
	ControlService_ConnectService_FullMethodName    = "/pollen.control.v1.ControlService/ConnectService"
	ControlService_ConnectPeer_FullMethodName       = "/pollen.control.v1.ControlService/ConnectPeer"
	ControlService_DisconnectService_FullMethodName = "/pollen.control.v1.ControlService/DisconnectService"
	ControlService_DenyPeer_FullMethodName          = "/pollen.control.v1.ControlService/DenyPeer"
	ControlService_SeedWorkload_FullMethodName      = "/pollen.control.v1.ControlService/SeedWorkload"
	ControlService_UnseedWorkload_FullMethodName    = "/pollen.control.v1.ControlService/UnseedWorkload"
	ControlService_CallWorkload_FullMethodName      = "/pollen.control.v1.ControlService/CallWorkload"
	ControlService_IssueCert_FullMethodName         = "/pollen.control.v1.ControlService/IssueCert"
	ControlService_FetchBlob_FullMethodName         = "/pollen.control.v1.ControlService/FetchBlob"
	ControlService_AnnounceBlob_FullMethodName      = "/pollen.control.v1.ControlService/AnnounceBlob"
	ControlService_RemoveBlob_FullMethodName        = "/pollen.control.v1.ControlService/RemoveBlob"
	ControlService_SeedStatic_FullMethodName        = "/pollen.control.v1.ControlService/SeedStatic"
	ControlService_UnseedStatic_FullMethodName      = "/pollen.control.v1.ControlService/UnseedStatic"
	ControlService_ListStatic_FullMethodName        = "/pollen.control.v1.ControlService/ListStatic"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	GetBootstrapInfo(ctx context.Context, in *GetBootstrapInfoRequest, opts ...grpc.CallOption) (*GetBootstrapInfoResponse, error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*UnregisterServiceResponse, error)
	ConnectService(ctx context.Context, in *ConnectServiceRequest, opts ...grpc.CallOption) (*ConnectServiceResponse, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	DisconnectService(ctx context.Context, in *DisconnectServiceRequest, opts ...grpc.CallOption) (*DisconnectServiceResponse, error)
	DenyPeer(ctx context.Context, in *DenyPeerRequest, opts ...grpc.CallOption) (*DenyPeerResponse, error)
	SeedWorkload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SeedWorkloadRequest, SeedWorkloadResponse], error)
	UnseedWorkload(ctx context.Context, in *UnseedWorkloadRequest, opts ...grpc.CallOption) (*UnseedWorkloadResponse, error)
	CallWorkload(ctx context.Context, in *CallWorkloadRequest, opts ...grpc.CallOption) (*CallWorkloadResponse, error)
	IssueCert(ctx context.Context, in *IssueCertRequest, opts ...grpc.CallOption) (*IssueCertResponse, error)
	FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (*FetchBlobResponse, error)
	AnnounceBlob(ctx context.Context, in *AnnounceBlobRequest, opts ...grpc.CallOption) (*AnnounceBlobResponse, error)
	RemoveBlob(ctx context.Context, in *RemoveBlobRequest, opts ...grpc.CallOption) (*RemoveBlobResponse, error)
	SeedStatic(ctx context.Context, in *SeedStaticRequest, opts ...grpc.CallOption) (*SeedStaticResponse, error)
	UnseedStatic(ctx context.Context, in *UnseedStaticRequest, opts ...grpc.CallOption) (*UnseedStaticResponse, error)
	ListStatic(ctx context.Context, in *ListStaticRequest, opts ...grpc.CallOption) (*ListStaticResponse, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ControlService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetBootstrapInfo(ctx context.Context, in *GetBootstrapInfoRequest, opts ...grpc.CallOption) (*GetBootstrapInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBootstrapInfoResponse)
	err := c.cc.Invoke(ctx, ControlService_GetBootstrapInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ControlService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ControlService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, ControlService_RegisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) UnregisterService(ctx context.Context, in *UnregisterServiceRequest, opts ...grpc.CallOption) (*UnregisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterServiceResponse)
	err := c.cc.Invoke(ctx, ControlService_UnregisterService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ConnectService(ctx context.Context, in *ConnectServiceRequest, opts ...grpc.CallOption) (*ConnectServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectServiceResponse)
	err := c.cc.Invoke(ctx, ControlService_ConnectService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectPeerResponse)
	err := c.cc.Invoke(ctx, ControlService_ConnectPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DisconnectService(ctx context.Context, in *DisconnectServiceRequest, opts ...grpc.CallOption) (*DisconnectServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectServiceResponse)
	err := c.cc.Invoke(ctx, ControlService_DisconnectService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) DenyPeer(ctx context.Context, in *DenyPeerRequest, opts ...grpc.CallOption) (*DenyPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DenyPeerResponse)
	err := c.cc.Invoke(ctx, ControlService_DenyPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SeedWorkload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SeedWorkloadRequest, SeedWorkloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_SeedWorkload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SeedWorkloadRequest, SeedWorkloadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_SeedWorkloadClient = grpc.ClientStreamingClient[SeedWorkloadRequest, SeedWorkloadResponse]

func (c *controlServiceClient) UnseedWorkload(ctx context.Context, in *UnseedWorkloadRequest, opts ...grpc.CallOption) (*UnseedWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnseedWorkloadResponse)
	err := c.cc.Invoke(ctx, ControlService_UnseedWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) CallWorkload(ctx context.Context, in *CallWorkloadRequest, opts ...grpc.CallOption) (*CallWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallWorkloadResponse)
	err := c.cc.Invoke(ctx, ControlService_CallWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) IssueCert(ctx context.Context, in *IssueCertRequest, opts ...grpc.CallOption) (*IssueCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCertResponse)
	err := c.cc.Invoke(ctx, ControlService_IssueCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) FetchBlob(ctx context.Context, in *FetchBlobRequest, opts ...grpc.CallOption) (*FetchBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchBlobResponse)
	err := c.cc.Invoke(ctx, ControlService_FetchBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) AnnounceBlob(ctx context.Context, in *AnnounceBlobRequest, opts ...grpc.CallOption) (*AnnounceBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceBlobResponse)
	err := c.cc.Invoke(ctx, ControlService_AnnounceBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) RemoveBlob(ctx context.Context, in *RemoveBlobRequest, opts ...grpc.CallOption) (*RemoveBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBlobResponse)
	err := c.cc.Invoke(ctx, ControlService_RemoveBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) SeedStatic(ctx context.Context, in *SeedStaticRequest, opts ...grpc.CallOption) (*SeedStaticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedStaticResponse)
	err := c.cc.Invoke(ctx, ControlService_SeedStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) UnseedStatic(ctx context.Context, in *UnseedStaticRequest, opts ...grpc.CallOption) (*UnseedStaticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnseedStaticResponse)
	err := c.cc.Invoke(ctx, ControlService_UnseedStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) ListStatic(ctx context.Context, in *ListStaticRequest, opts ...grpc.CallOption) (*ListStaticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStaticResponse)
	err := c.cc.Invoke(ctx, ControlService_ListStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility.
type ControlServiceServer interface {
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	GetBootstrapInfo(context.Context, *GetBootstrapInfoRequest) (*GetBootstrapInfoResponse, error)
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	UnregisterService(context.Context, *UnregisterServiceRequest) (*UnregisterServiceResponse, error)
	ConnectService(context.Context, *ConnectServiceRequest) (*ConnectServiceResponse, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	DisconnectService(context.Context, *DisconnectServiceRequest) (*DisconnectServiceResponse, error)
	DenyPeer(context.Context, *DenyPeerRequest) (*DenyPeerResponse, error)
	SeedWorkload(grpc.ClientStreamingServer[SeedWorkloadRequest, SeedWorkloadResponse]) error
	UnseedWorkload(context.Context, *UnseedWorkloadRequest) (*UnseedWorkloadResponse, error)
	CallWorkload(context.Context, *CallWorkloadRequest) (*CallWorkloadResponse, error)
	IssueCert(context.Context, *IssueCertRequest) (*IssueCertResponse, error)
	FetchBlob(context.Context, *FetchBlobRequest) (*FetchBlobResponse, error)
	AnnounceBlob(context.Context, *AnnounceBlobRequest) (*AnnounceBlobResponse, error)
	RemoveBlob(context.Context, *RemoveBlobRequest) (*RemoveBlobResponse, error)
	SeedStatic(context.Context, *SeedStaticRequest) (*SeedStaticResponse, error)
	UnseedStatic(context.Context, *UnseedStaticRequest) (*UnseedStaticResponse, error)
	ListStatic(context.Context, *ListStaticRequest) (*ListStaticResponse, error)
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServiceServer struct{}

func (UnimplementedControlServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedControlServiceServer) GetBootstrapInfo(context.Context, *GetBootstrapInfoRequest) (*GetBootstrapInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBootstrapInfo not implemented")
}
func (UnimplementedControlServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedControlServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedControlServiceServer) RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterService not implemented")
}
func (UnimplementedControlServiceServer) UnregisterService(context.Context, *UnregisterServiceRequest) (*UnregisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterService not implemented")
}
func (UnimplementedControlServiceServer) ConnectService(context.Context, *ConnectServiceRequest) (*ConnectServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectService not implemented")
}
func (UnimplementedControlServiceServer) ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (UnimplementedControlServiceServer) DisconnectService(context.Context, *DisconnectServiceRequest) (*DisconnectServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectService not implemented")
}
func (UnimplementedControlServiceServer) DenyPeer(context.Context, *DenyPeerRequest) (*DenyPeerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DenyPeer not implemented")
}
func (UnimplementedControlServiceServer) SeedWorkload(grpc.ClientStreamingServer[SeedWorkloadRequest, SeedWorkloadResponse]) error {
	return status.Error(codes.Unimplemented, "method SeedWorkload not implemented")
}
func (UnimplementedControlServiceServer) UnseedWorkload(context.Context, *UnseedWorkloadRequest) (*UnseedWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnseedWorkload not implemented")
}
func (UnimplementedControlServiceServer) CallWorkload(context.Context, *CallWorkloadRequest) (*CallWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallWorkload not implemented")
}
func (UnimplementedControlServiceServer) IssueCert(context.Context, *IssueCertRequest) (*IssueCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCert not implemented")
}
func (UnimplementedControlServiceServer) FetchBlob(context.Context, *FetchBlobRequest) (*FetchBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchBlob not implemented")
}
func (UnimplementedControlServiceServer) AnnounceBlob(context.Context, *AnnounceBlobRequest) (*AnnounceBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceBlob not implemented")
}
func (UnimplementedControlServiceServer) RemoveBlob(context.Context, *RemoveBlobRequest) (*RemoveBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBlob not implemented")
}
func (UnimplementedControlServiceServer) SeedStatic(context.Context, *SeedStaticRequest) (*SeedStaticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeedStatic not implemented")
}
func (UnimplementedControlServiceServer) UnseedStatic(context.Context, *UnseedStaticRequest) (*UnseedStaticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnseedStatic not implemented")
}
func (UnimplementedControlServiceServer) ListStatic(context.Context, *ListStaticRequest) (*ListStaticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStatic not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}
func (UnimplementedControlServiceServer) testEmbeddedByValue()                        {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	// If the following call panics, it indicates UnimplementedControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetBootstrapInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBootstrapInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetBootstrapInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetBootstrapInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetBootstrapInfo(ctx, req.(*GetBootstrapInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RegisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_UnregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).UnregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_UnregisterService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).UnregisterService(ctx, req.(*UnregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ConnectService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ConnectService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ConnectService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ConnectService(ctx, req.(*ConnectServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ConnectPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DisconnectService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DisconnectService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DisconnectService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DisconnectService(ctx, req.(*DisconnectServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_DenyPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DenyPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).DenyPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_DenyPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).DenyPeer(ctx, req.(*DenyPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SeedWorkload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).SeedWorkload(&grpc.GenericServerStream[SeedWorkloadRequest, SeedWorkloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControlService_SeedWorkloadServer = grpc.ClientStreamingServer[SeedWorkloadRequest, SeedWorkloadResponse]

func _ControlService_UnseedWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnseedWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).UnseedWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_UnseedWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).UnseedWorkload(ctx, req.(*UnseedWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_CallWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).CallWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_CallWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).CallWorkload(ctx, req.(*CallWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_IssueCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).IssueCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_IssueCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).IssueCert(ctx, req.(*IssueCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_FetchBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).FetchBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_FetchBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).FetchBlob(ctx, req.(*FetchBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_AnnounceBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).AnnounceBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_AnnounceBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).AnnounceBlob(ctx, req.(*AnnounceBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_RemoveBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).RemoveBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_RemoveBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).RemoveBlob(ctx, req.(*RemoveBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_SeedStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedStaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).SeedStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_SeedStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).SeedStatic(ctx, req.(*SeedStaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_UnseedStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnseedStaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).UnseedStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_UnseedStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).UnseedStatic(ctx, req.(*UnseedStaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_ListStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).ListStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlService_ListStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).ListStatic(ctx, req.(*ListStaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pollen.control.v1.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _ControlService_Shutdown_Handler,
		},
		{
			MethodName: "GetBootstrapInfo",
			Handler:    _ControlService_GetBootstrapInfo_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ControlService_GetStatus_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ControlService_GetMetrics_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _ControlService_RegisterService_Handler,
		},
		{
			MethodName: "UnregisterService",
			Handler:    _ControlService_UnregisterService_Handler,
		},
		{
			MethodName: "ConnectService",
			Handler:    _ControlService_ConnectService_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _ControlService_ConnectPeer_Handler,
		},
		{
			MethodName: "DisconnectService",
			Handler:    _ControlService_DisconnectService_Handler,
		},
		{
			MethodName: "DenyPeer",
			Handler:    _ControlService_DenyPeer_Handler,
		},
		{
			MethodName: "UnseedWorkload",
			Handler:    _ControlService_UnseedWorkload_Handler,
		},
		{
			MethodName: "CallWorkload",
			Handler:    _ControlService_CallWorkload_Handler,
		},
		{
			MethodName: "IssueCert",
			Handler:    _ControlService_IssueCert_Handler,
		},
		{
			MethodName: "FetchBlob",
			Handler:    _ControlService_FetchBlob_Handler,
		},
		{
			MethodName: "AnnounceBlob",
			Handler:    _ControlService_AnnounceBlob_Handler,
		},
		{
			MethodName: "RemoveBlob",
			Handler:    _ControlService_RemoveBlob_Handler,
		},
		{
			MethodName: "SeedStatic",
			Handler:    _ControlService_SeedStatic_Handler,
		},
		{
			MethodName: "UnseedStatic",
			Handler:    _ControlService_UnseedStatic_Handler,
		},
		{
			MethodName: "ListStatic",
			Handler:    _ControlService_ListStatic_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SeedWorkload",
			Handler:       _ControlService_SeedWorkload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pollen/control/v1/control.proto",
}
