// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pollen/mesh/v1/mesh.proto

package meshv1

import (
	v1 "github.com/sambigeara/pollen/api/genpb/pollen/admission/v1"
	v11 "github.com/sambigeara/pollen/api/genpb/pollen/state/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PunchCoordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchCoordRequest) Reset() {
	*x = PunchCoordRequest{}
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchCoordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchCoordRequest) ProtoMessage() {}

func (x *PunchCoordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchCoordRequest.ProtoReflect.Descriptor instead.
func (*PunchCoordRequest) Descriptor() ([]byte, []int) {
	return file_pollen_mesh_v1_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *PunchCoordRequest) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

type PunchCoordTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	SelfAddr      string                 `protobuf:"bytes,2,opt,name=self_addr,json=selfAddr,proto3" json:"self_addr,omitempty"`
	PeerAddr      string                 `protobuf:"bytes,3,opt,name=peer_addr,json=peerAddr,proto3" json:"peer_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchCoordTrigger) Reset() {
	*x = PunchCoordTrigger{}
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchCoordTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchCoordTrigger) ProtoMessage() {}

func (x *PunchCoordTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchCoordTrigger.ProtoReflect.Descriptor instead.
func (*PunchCoordTrigger) Descriptor() ([]byte, []int) {
	return file_pollen_mesh_v1_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *PunchCoordTrigger) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *PunchCoordTrigger) GetSelfAddr() string {
	if x != nil {
		return x.SelfAddr
	}
	return ""
}

func (x *PunchCoordTrigger) GetPeerAddr() string {
	if x != nil {
		return x.PeerAddr
	}
	return ""
}

type InviteRedeemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *v1.InviteToken        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SubjectPub    []byte                 `protobuf:"bytes,2,opt,name=subject_pub,json=subjectPub,proto3" json:"subject_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRedeemRequest) Reset() {
	*x = InviteRedeemRequest{}
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRedeemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRedeemRequest) ProtoMessage() {}

func (x *InviteRedeemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRedeemRequest.ProtoReflect.Descriptor instead.
func (*InviteRedeemRequest) Descriptor() ([]byte, []int) {
	return file_pollen_mesh_v1_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *InviteRedeemRequest) GetToken() *v1.InviteToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *InviteRedeemRequest) GetSubjectPub() []byte {
	if x != nil {
		return x.SubjectPub
	}
	return nil
}

type InviteRedeemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	JoinToken     *v1.JoinToken          `protobuf:"bytes,3,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRedeemResponse) Reset() {
	*x = InviteRedeemResponse{}
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRedeemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRedeemResponse) ProtoMessage() {}

func (x *InviteRedeemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRedeemResponse.ProtoReflect.Descriptor instead.
func (*InviteRedeemResponse) Descriptor() ([]byte, []int) {
	return file_pollen_mesh_v1_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *InviteRedeemResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InviteRedeemResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InviteRedeemResponse) GetJoinToken() *v1.JoinToken {
	if x != nil {
		return x.JoinToken
	}
	return nil
}

type ObservedAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedAddress) Reset() {
	*x = ObservedAddress{}
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedAddress) ProtoMessage() {}

func (x *ObservedAddress) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedAddress.ProtoReflect.Descriptor instead.
func (*ObservedAddress) Descriptor() ([]byte, []int) {
	return file_pollen_mesh_v1_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *ObservedAddress) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Clock
	//	*Envelope_PunchCoordRequest
	//	*Envelope_PunchCoordTrigger
	//	*Envelope_InviteRedeemRequest
	//	*Envelope_InviteRedeemResponse
	//	*Envelope_ObservedAddress
	//	*Envelope_Events
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_mesh_v1_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_pollen_mesh_v1_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetClock() *v11.GossipVectorClock {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Clock); ok {
			return x.Clock
		}
	}
	return nil
}

func (x *Envelope) GetPunchCoordRequest() *PunchCoordRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PunchCoordRequest); ok {
			return x.PunchCoordRequest
		}
	}
	return nil
}

func (x *Envelope) GetPunchCoordTrigger() *PunchCoordTrigger {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PunchCoordTrigger); ok {
			return x.PunchCoordTrigger
		}
	}
	return nil
}

func (x *Envelope) GetInviteRedeemRequest() *InviteRedeemRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_InviteRedeemRequest); ok {
			return x.InviteRedeemRequest
		}
	}
	return nil
}

func (x *Envelope) GetInviteRedeemResponse() *InviteRedeemResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_InviteRedeemResponse); ok {
			return x.InviteRedeemResponse
		}
	}
	return nil
}

func (x *Envelope) GetObservedAddress() *ObservedAddress {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ObservedAddress); ok {
			return x.ObservedAddress
		}
	}
	return nil
}

func (x *Envelope) GetEvents() *v11.GossipEventBatch {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Events); ok {
			return x.Events
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Clock struct {
	Clock *v11.GossipVectorClock `protobuf:"bytes,1,opt,name=clock,proto3,oneof"`
}

type Envelope_PunchCoordRequest struct {
	PunchCoordRequest *PunchCoordRequest `protobuf:"bytes,3,opt,name=punch_coord_request,json=punchCoordRequest,proto3,oneof"`
}

type Envelope_PunchCoordTrigger struct {
	PunchCoordTrigger *PunchCoordTrigger `protobuf:"bytes,4,opt,name=punch_coord_trigger,json=punchCoordTrigger,proto3,oneof"`
}

type Envelope_InviteRedeemRequest struct {
	InviteRedeemRequest *InviteRedeemRequest `protobuf:"bytes,6,opt,name=invite_redeem_request,json=inviteRedeemRequest,proto3,oneof"`
}

type Envelope_InviteRedeemResponse struct {
	InviteRedeemResponse *InviteRedeemResponse `protobuf:"bytes,7,opt,name=invite_redeem_response,json=inviteRedeemResponse,proto3,oneof"`
}

type Envelope_ObservedAddress struct {
	ObservedAddress *ObservedAddress `protobuf:"bytes,8,opt,name=observed_address,json=observedAddress,proto3,oneof"`
}

type Envelope_Events struct {
	Events *v11.GossipEventBatch `protobuf:"bytes,9,opt,name=events,proto3,oneof"`
}

func (*Envelope_Clock) isEnvelope_Body() {}

func (*Envelope_PunchCoordRequest) isEnvelope_Body() {}

func (*Envelope_PunchCoordTrigger) isEnvelope_Body() {}

func (*Envelope_InviteRedeemRequest) isEnvelope_Body() {}

func (*Envelope_InviteRedeemResponse) isEnvelope_Body() {}

func (*Envelope_ObservedAddress) isEnvelope_Body() {}

func (*Envelope_Events) isEnvelope_Body() {}

var File_pollen_mesh_v1_mesh_proto protoreflect.FileDescriptor

const file_pollen_mesh_v1_mesh_proto_rawDesc = "" +
	"\n" +
	"\x19pollen/mesh/v1/mesh.proto\x12\x0epollen.mesh.v1\x1a#pollen/admission/v1/admission.proto\x1a\x1bpollen/state/v1/state.proto\",\n" +
	"\x11PunchCoordRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\"f\n" +
	"\x11PunchCoordTrigger\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\fR\x06peerId\x12\x1b\n" +
	"\tself_addr\x18\x02 \x01(\tR\bselfAddr\x12\x1b\n" +
	"\tpeer_addr\x18\x03 \x01(\tR\bpeerAddr\"n\n" +
	"\x13InviteRedeemRequest\x126\n" +
	"\x05token\x18\x01 \x01(\v2 .pollen.admission.v1.InviteTokenR\x05token\x12\x1f\n" +
	"\vsubject_pub\x18\x02 \x01(\fR\n" +
	"subjectPub\"\x89\x01\n" +
	"\x14InviteRedeemResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12=\n" +
	"\n" +
	"join_token\x18\x03 \x01(\v2\x1e.pollen.admission.v1.JoinTokenR\tjoinToken\"%\n" +
	"\x0fObservedAddress\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\xbc\x04\n" +
	"\bEnvelope\x12:\n" +
	"\x05clock\x18\x01 \x01(\v2\".pollen.state.v1.GossipVectorClockH\x00R\x05clock\x12S\n" +
	"\x13punch_coord_request\x18\x03 \x01(\v2!.pollen.mesh.v1.PunchCoordRequestH\x00R\x11punchCoordRequest\x12S\n" +
	"\x13punch_coord_trigger\x18\x04 \x01(\v2!.pollen.mesh.v1.PunchCoordTriggerH\x00R\x11punchCoordTrigger\x12Y\n" +
	"\x15invite_redeem_request\x18\x06 \x01(\v2#.pollen.mesh.v1.InviteRedeemRequestH\x00R\x13inviteRedeemRequest\x12\\\n" +
	"\x16invite_redeem_response\x18\a \x01(\v2$.pollen.mesh.v1.InviteRedeemResponseH\x00R\x14inviteRedeemResponse\x12L\n" +
	"\x10observed_address\x18\b \x01(\v2\x1f.pollen.mesh.v1.ObservedAddressH\x00R\x0fobservedAddress\x12;\n" +
	"\x06events\x18\t \x01(\v2!.pollen.state.v1.GossipEventBatchH\x00R\x06eventsB\x06\n" +
	"\x04bodyB>Z<github.com/sambigeara/pollen/api/genpb/pollen/mesh/v1;meshv1b\x06proto3"

var (
	file_pollen_mesh_v1_mesh_proto_rawDescOnce sync.Once
	file_pollen_mesh_v1_mesh_proto_rawDescData []byte
)

func file_pollen_mesh_v1_mesh_proto_rawDescGZIP() []byte {
	file_pollen_mesh_v1_mesh_proto_rawDescOnce.Do(func() {
		file_pollen_mesh_v1_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pollen_mesh_v1_mesh_proto_rawDesc), len(file_pollen_mesh_v1_mesh_proto_rawDesc)))
	})
	return file_pollen_mesh_v1_mesh_proto_rawDescData
}

var file_pollen_mesh_v1_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pollen_mesh_v1_mesh_proto_goTypes = []any{
	(*PunchCoordRequest)(nil),     // 0: pollen.mesh.v1.PunchCoordRequest
	(*PunchCoordTrigger)(nil),     // 1: pollen.mesh.v1.PunchCoordTrigger
	(*InviteRedeemRequest)(nil),   // 2: pollen.mesh.v1.InviteRedeemRequest
	(*InviteRedeemResponse)(nil),  // 3: pollen.mesh.v1.InviteRedeemResponse
	(*ObservedAddress)(nil),       // 4: pollen.mesh.v1.ObservedAddress
	(*Envelope)(nil),              // 5: pollen.mesh.v1.Envelope
	(*v1.InviteToken)(nil),        // 6: pollen.admission.v1.InviteToken
	(*v1.JoinToken)(nil),          // 7: pollen.admission.v1.JoinToken
	(*v11.GossipVectorClock)(nil), // 8: pollen.state.v1.GossipVectorClock
	(*v11.GossipEventBatch)(nil),  // 9: pollen.state.v1.GossipEventBatch
}
var file_pollen_mesh_v1_mesh_proto_depIdxs = []int32{
	6, // 0: pollen.mesh.v1.InviteRedeemRequest.token:type_name -> pollen.admission.v1.InviteToken
	7, // 1: pollen.mesh.v1.InviteRedeemResponse.join_token:type_name -> pollen.admission.v1.JoinToken
	8, // 2: pollen.mesh.v1.Envelope.clock:type_name -> pollen.state.v1.GossipVectorClock
	0, // 3: pollen.mesh.v1.Envelope.punch_coord_request:type_name -> pollen.mesh.v1.PunchCoordRequest
	1, // 4: pollen.mesh.v1.Envelope.punch_coord_trigger:type_name -> pollen.mesh.v1.PunchCoordTrigger
	2, // 5: pollen.mesh.v1.Envelope.invite_redeem_request:type_name -> pollen.mesh.v1.InviteRedeemRequest
	3, // 6: pollen.mesh.v1.Envelope.invite_redeem_response:type_name -> pollen.mesh.v1.InviteRedeemResponse
	4, // 7: pollen.mesh.v1.Envelope.observed_address:type_name -> pollen.mesh.v1.ObservedAddress
	9, // 8: pollen.mesh.v1.Envelope.events:type_name -> pollen.state.v1.GossipEventBatch
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pollen_mesh_v1_mesh_proto_init() }
func file_pollen_mesh_v1_mesh_proto_init() {
	if File_pollen_mesh_v1_mesh_proto != nil {
		return
	}
	file_pollen_mesh_v1_mesh_proto_msgTypes[5].OneofWrappers = []any{
		(*Envelope_Clock)(nil),
		(*Envelope_PunchCoordRequest)(nil),
		(*Envelope_PunchCoordTrigger)(nil),
		(*Envelope_InviteRedeemRequest)(nil),
		(*Envelope_InviteRedeemResponse)(nil),
		(*Envelope_ObservedAddress)(nil),
		(*Envelope_Events)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pollen_mesh_v1_mesh_proto_rawDesc), len(file_pollen_mesh_v1_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pollen_mesh_v1_mesh_proto_goTypes,
		DependencyIndexes: file_pollen_mesh_v1_mesh_proto_depIdxs,
		MessageInfos:      file_pollen_mesh_v1_mesh_proto_msgTypes,
	}.Build()
	File_pollen_mesh_v1_mesh_proto = out.File
	file_pollen_mesh_v1_mesh_proto_goTypes = nil
	file_pollen_mesh_v1_mesh_proto_depIdxs = nil
}
