// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pollen/control/v1/control.proto

package controlv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/sambigeara/pollen/api/genpb/pollen/control/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControlServiceName is the fully-qualified name of the ControlService service.
	ControlServiceName = "pollen.control.v1.ControlService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControlServiceListPeersProcedure is the fully-qualified name of the ControlService's ListPeers
	// RPC.
	ControlServiceListPeersProcedure = "/pollen.control.v1.ControlService/ListPeers"
)

// ControlServiceClient is a client for the pollen.control.v1.ControlService service.
type ControlServiceClient interface {
	ListPeers(context.Context, *connect.Request[v1.ListPeersRequest]) (*connect.Response[v1.ListPeersResponse], error)
}

// NewControlServiceClient constructs a client for the pollen.control.v1.ControlService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controlServiceMethods := v1.File_pollen_control_v1_control_proto.Services().ByName("ControlService").Methods()
	return &controlServiceClient{
		listPeers: connect.NewClient[v1.ListPeersRequest, v1.ListPeersResponse](
			httpClient,
			baseURL+ControlServiceListPeersProcedure,
			connect.WithSchema(controlServiceMethods.ByName("ListPeers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controlServiceClient implements ControlServiceClient.
type controlServiceClient struct {
	listPeers *connect.Client[v1.ListPeersRequest, v1.ListPeersResponse]
}

// ListPeers calls pollen.control.v1.ControlService.ListPeers.
func (c *controlServiceClient) ListPeers(ctx context.Context, req *connect.Request[v1.ListPeersRequest]) (*connect.Response[v1.ListPeersResponse], error) {
	return c.listPeers.CallUnary(ctx, req)
}

// ControlServiceHandler is an implementation of the pollen.control.v1.ControlService service.
type ControlServiceHandler interface {
	ListPeers(context.Context, *connect.Request[v1.ListPeersRequest]) (*connect.Response[v1.ListPeersResponse], error)
}

// NewControlServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControlServiceHandler(svc ControlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controlServiceMethods := v1.File_pollen_control_v1_control_proto.Services().ByName("ControlService").Methods()
	controlServiceListPeersHandler := connect.NewUnaryHandler(
		ControlServiceListPeersProcedure,
		svc.ListPeers,
		connect.WithSchema(controlServiceMethods.ByName("ListPeers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pollen.control.v1.ControlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControlServiceListPeersProcedure:
			controlServiceListPeersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControlServiceHandler struct{}

func (UnimplementedControlServiceHandler) ListPeers(context.Context, *connect.Request[v1.ListPeersRequest]) (*connect.Response[v1.ListPeersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pollen.control.v1.ControlService.ListPeers is not implemented"))
}
