// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pollen/state/v1/gossip.proto

package statev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/sambigeara/pollen/api/genpb/pollen/peer/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type GossipVectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counters      map[string]uint64      `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipVectorClock) Reset() {
	*x = GossipVectorClock{}
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipVectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipVectorClock) ProtoMessage() {}

func (x *GossipVectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipVectorClock.ProtoReflect.Descriptor instead.
func (*GossipVectorClock) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *GossipVectorClock) GetCounters() map[string]uint64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

type GossipNode struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeerId         string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Counter        uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	IdentityPub    []byte                 `protobuf:"bytes,3,opt,name=identity_pub,json=identityPub,proto3" json:"identity_pub,omitempty"`
	Ips            []string               `protobuf:"bytes,4,rep,name=ips,proto3" json:"ips,omitempty"`
	LocalPort      uint32                 `protobuf:"varint,5,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	Services       []*Service             `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	ReachablePeers []string               `protobuf:"bytes,7,rep,name=reachable_peers,json=reachablePeers,proto3" json:"reachable_peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GossipNode) Reset() {
	*x = GossipNode{}
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipNode) ProtoMessage() {}

func (x *GossipNode) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipNode.ProtoReflect.Descriptor instead.
func (*GossipNode) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *GossipNode) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GossipNode) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *GossipNode) GetIdentityPub() []byte {
	if x != nil {
		return x.IdentityPub
	}
	return nil
}

func (x *GossipNode) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *GossipNode) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *GossipNode) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GossipNode) GetReachablePeers() []string {
	if x != nil {
		return x.ReachablePeers
	}
	return nil
}

type DatagramEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*DatagramEnvelope_Clock
	//	*DatagramEnvelope_Node
	//	*DatagramEnvelope_PunchCoordRequest
	//	*DatagramEnvelope_PunchCoordTrigger
	Body          isDatagramEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatagramEnvelope) Reset() {
	*x = DatagramEnvelope{}
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatagramEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatagramEnvelope) ProtoMessage() {}

func (x *DatagramEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatagramEnvelope.ProtoReflect.Descriptor instead.
func (*DatagramEnvelope) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *DatagramEnvelope) GetBody() isDatagramEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DatagramEnvelope) GetClock() *GossipVectorClock {
	if x != nil {
		if x, ok := x.Body.(*DatagramEnvelope_Clock); ok {
			return x.Clock
		}
	}
	return nil
}

func (x *DatagramEnvelope) GetNode() *GossipNode {
	if x != nil {
		if x, ok := x.Body.(*DatagramEnvelope_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *DatagramEnvelope) GetPunchCoordRequest() *v1.PunchCoordRequest {
	if x != nil {
		if x, ok := x.Body.(*DatagramEnvelope_PunchCoordRequest); ok {
			return x.PunchCoordRequest
		}
	}
	return nil
}

func (x *DatagramEnvelope) GetPunchCoordTrigger() *v1.PunchCoordTrigger {
	if x != nil {
		if x, ok := x.Body.(*DatagramEnvelope_PunchCoordTrigger); ok {
			return x.PunchCoordTrigger
		}
	}
	return nil
}

type isDatagramEnvelope_Body interface {
	isDatagramEnvelope_Body()
}

type DatagramEnvelope_Clock struct {
	Clock *GossipVectorClock `protobuf:"bytes,1,opt,name=clock,proto3,oneof"`
}

type DatagramEnvelope_Node struct {
	Node *GossipNode `protobuf:"bytes,2,opt,name=node,proto3,oneof"`
}

type DatagramEnvelope_PunchCoordRequest struct {
	PunchCoordRequest *v1.PunchCoordRequest `protobuf:"bytes,3,opt,name=punch_coord_request,json=punchCoordRequest,proto3,oneof"`
}

type DatagramEnvelope_PunchCoordTrigger struct {
	PunchCoordTrigger *v1.PunchCoordTrigger `protobuf:"bytes,4,opt,name=punch_coord_trigger,json=punchCoordTrigger,proto3,oneof"`
}

func (*DatagramEnvelope_Clock) isDatagramEnvelope_Body() {}

func (*DatagramEnvelope_Node) isDatagramEnvelope_Body() {}

func (*DatagramEnvelope_PunchCoordRequest) isDatagramEnvelope_Body() {}

func (*DatagramEnvelope_PunchCoordTrigger) isDatagramEnvelope_Body() {}

var File_pollen_state_v1_gossip_proto protoreflect.FileDescriptor

const file_pollen_state_v1_gossip_proto_rawDesc = "" +
	"\n" +
	"\x1cpollen/state/v1/gossip.proto\x12\x0fpollen.state.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19pollen/peer/v1/peer.proto\">\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x04port\x18\x02 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\x04port\"\x9e\x01\n" +
	"\x11GossipVectorClock\x12L\n" +
	"\bcounters\x18\x01 \x03(\v20.pollen.state.v1.GossipVectorClock.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xa5\x02\n" +
	"\n" +
	"GossipNode\x124\n" +
	"\apeer_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x162\x11^[a-fA-F0-9]{64}$\x98\x01@R\x06peerId\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\x12*\n" +
	"\fidentity_pub\x18\x03 \x01(\fB\a\xbaH\x04z\x02h R\videntityPub\x12\x10\n" +
	"\x03ips\x18\x04 \x03(\tR\x03ips\x12*\n" +
	"\n" +
	"local_port\x18\x05 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03 \x00R\tlocalPort\x124\n" +
	"\bservices\x18\x06 \x03(\v2\x18.pollen.state.v1.ServiceR\bservices\x12'\n" +
	"\x0freachable_peers\x18\a \x03(\tR\x0ereachablePeers\"\xb3\x02\n" +
	"\x10DatagramEnvelope\x12:\n" +
	"\x05clock\x18\x01 \x01(\v2\".pollen.state.v1.GossipVectorClockH\x00R\x05clock\x121\n" +
	"\x04node\x18\x02 \x01(\v2\x1b.pollen.state.v1.GossipNodeH\x00R\x04node\x12S\n" +
	"\x13punch_coord_request\x18\x03 \x01(\v2!.pollen.peer.v1.PunchCoordRequestH\x00R\x11punchCoordRequest\x12S\n" +
	"\x13punch_coord_trigger\x18\x04 \x01(\v2!.pollen.peer.v1.PunchCoordTriggerH\x00R\x11punchCoordTriggerB\x06\n" +
	"\x04bodyB@Z>github.com/sambigeara/pollen/api/genpb/pollen/state/v1;statev1b\x06proto3"

var (
	file_pollen_state_v1_gossip_proto_rawDescOnce sync.Once
	file_pollen_state_v1_gossip_proto_rawDescData []byte
)

func file_pollen_state_v1_gossip_proto_rawDescGZIP() []byte {
	file_pollen_state_v1_gossip_proto_rawDescOnce.Do(func() {
		file_pollen_state_v1_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pollen_state_v1_gossip_proto_rawDesc), len(file_pollen_state_v1_gossip_proto_rawDesc)))
	})
	return file_pollen_state_v1_gossip_proto_rawDescData
}

var file_pollen_state_v1_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pollen_state_v1_gossip_proto_goTypes = []any{
	(*Service)(nil),              // 0: pollen.state.v1.Service
	(*GossipVectorClock)(nil),    // 1: pollen.state.v1.GossipVectorClock
	(*GossipNode)(nil),           // 2: pollen.state.v1.GossipNode
	(*DatagramEnvelope)(nil),     // 3: pollen.state.v1.DatagramEnvelope
	nil,                          // 4: pollen.state.v1.GossipVectorClock.CountersEntry
	(*v1.PunchCoordRequest)(nil), // 5: pollen.peer.v1.PunchCoordRequest
	(*v1.PunchCoordTrigger)(nil), // 6: pollen.peer.v1.PunchCoordTrigger
}
var file_pollen_state_v1_gossip_proto_depIdxs = []int32{
	4, // 0: pollen.state.v1.GossipVectorClock.counters:type_name -> pollen.state.v1.GossipVectorClock.CountersEntry
	0, // 1: pollen.state.v1.GossipNode.services:type_name -> pollen.state.v1.Service
	1, // 2: pollen.state.v1.DatagramEnvelope.clock:type_name -> pollen.state.v1.GossipVectorClock
	2, // 3: pollen.state.v1.DatagramEnvelope.node:type_name -> pollen.state.v1.GossipNode
	5, // 4: pollen.state.v1.DatagramEnvelope.punch_coord_request:type_name -> pollen.peer.v1.PunchCoordRequest
	6, // 5: pollen.state.v1.DatagramEnvelope.punch_coord_trigger:type_name -> pollen.peer.v1.PunchCoordTrigger
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pollen_state_v1_gossip_proto_init() }
func file_pollen_state_v1_gossip_proto_init() {
	if File_pollen_state_v1_gossip_proto != nil {
		return
	}
	file_pollen_state_v1_gossip_proto_msgTypes[3].OneofWrappers = []any{
		(*DatagramEnvelope_Clock)(nil),
		(*DatagramEnvelope_Node)(nil),
		(*DatagramEnvelope_PunchCoordRequest)(nil),
		(*DatagramEnvelope_PunchCoordTrigger)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pollen_state_v1_gossip_proto_rawDesc), len(file_pollen_state_v1_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pollen_state_v1_gossip_proto_goTypes,
		DependencyIndexes: file_pollen_state_v1_gossip_proto_depIdxs,
		MessageInfos:      file_pollen_state_v1_gossip_proto_msgTypes,
	}.Build()
	File_pollen_state_v1_gossip_proto = out.File
	file_pollen_state_v1_gossip_proto_goTypes = nil
	file_pollen_state_v1_gossip_proto_depIdxs = nil
}
