// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pollen/state/v1/state.proto

package statev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceProtocol int32

const (
	ServiceProtocol_SERVICE_PROTOCOL_UNSPECIFIED ServiceProtocol = 0
	ServiceProtocol_SERVICE_PROTOCOL_TCP         ServiceProtocol = 1
	ServiceProtocol_SERVICE_PROTOCOL_UDP         ServiceProtocol = 2
)

// Enum value maps for ServiceProtocol.
var (
	ServiceProtocol_name = map[int32]string{
		0: "SERVICE_PROTOCOL_UNSPECIFIED",
		1: "SERVICE_PROTOCOL_TCP",
		2: "SERVICE_PROTOCOL_UDP",
	}
	ServiceProtocol_value = map[string]int32{
		"SERVICE_PROTOCOL_UNSPECIFIED": 0,
		"SERVICE_PROTOCOL_TCP":         1,
		"SERVICE_PROTOCOL_UDP":         2,
	}
)

func (x ServiceProtocol) Enum() *ServiceProtocol {
	p := new(ServiceProtocol)
	*p = x
	return p
}

func (x ServiceProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_pollen_state_v1_state_proto_enumTypes[0].Descriptor()
}

func (ServiceProtocol) Type() protoreflect.EnumType {
	return &file_pollen_state_v1_state_proto_enumTypes[0]
}

func (x ServiceProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceProtocol.Descriptor instead.
func (ServiceProtocol) EnumDescriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{0}
}

type PeerDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCounter    uint64                 `protobuf:"varint,1,opt,name=max_counter,json=maxCounter,proto3" json:"max_counter,omitempty"`
	StateHash     uint64                 `protobuf:"fixed64,2,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDigest) Reset() {
	*x = PeerDigest{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDigest) ProtoMessage() {}

func (x *PeerDigest) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDigest.ProtoReflect.Descriptor instead.
func (*PeerDigest) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *PeerDigest) GetMaxCounter() uint64 {
	if x != nil {
		return x.MaxCounter
	}
	return 0
}

func (x *PeerDigest) GetStateHash() uint64 {
	if x != nil {
		return x.StateHash
	}
	return 0
}

type Digest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         map[string]*PeerDigest `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *Digest) GetPeers() map[string]*PeerDigest {
	if x != nil {
		return x.Peers
	}
	return nil
}

type ServiceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      ServiceProtocol        `protobuf:"varint,3,opt,name=protocol,proto3,enum=pollen.state.v1.ServiceProtocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceChange) Reset() {
	*x = ServiceChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceChange) ProtoMessage() {}

func (x *ServiceChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceChange.ProtoReflect.Descriptor instead.
func (*ServiceChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceChange) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceChange) GetProtocol() ServiceProtocol {
	if x != nil {
		return x.Protocol
	}
	return ServiceProtocol_SERVICE_PROTOCOL_UNSPECIFIED
}

type ReachabilityChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReachabilityChange) Reset() {
	*x = ReachabilityChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReachabilityChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReachabilityChange) ProtoMessage() {}

func (x *ReachabilityChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReachabilityChange.ProtoReflect.Descriptor instead.
func (*ReachabilityChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *ReachabilityChange) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type NetworkChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	LocalPort     uint32                 `protobuf:"varint,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkChange) Reset() {
	*x = NetworkChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkChange) ProtoMessage() {}

func (x *NetworkChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkChange.ProtoReflect.Descriptor instead.
func (*NetworkChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkChange) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *NetworkChange) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

type ObservedAddressChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedAddressChange) Reset() {
	*x = ObservedAddressChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedAddressChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedAddressChange) ProtoMessage() {}

func (x *ObservedAddressChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedAddressChange.ProtoReflect.Descriptor instead.
func (*ObservedAddressChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *ObservedAddressChange) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ObservedAddressChange) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PubliclyAccessibleChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubliclyAccessibleChange) Reset() {
	*x = PubliclyAccessibleChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubliclyAccessibleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubliclyAccessibleChange) ProtoMessage() {}

func (x *PubliclyAccessibleChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubliclyAccessibleChange.ProtoReflect.Descriptor instead.
func (*PubliclyAccessibleChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{6}
}

type VivaldiCoordinateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	Error         float64                `protobuf:"fixed64,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VivaldiCoordinateChange) Reset() {
	*x = VivaldiCoordinateChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VivaldiCoordinateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VivaldiCoordinateChange) ProtoMessage() {}

func (x *VivaldiCoordinateChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VivaldiCoordinateChange.ProtoReflect.Descriptor instead.
func (*VivaldiCoordinateChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *VivaldiCoordinateChange) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VivaldiCoordinateChange) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *VivaldiCoordinateChange) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VivaldiCoordinateChange) GetError() float64 {
	if x != nil {
		return x.Error
	}
	return 0
}

type CertExpiryChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiryUnix    int64                  `protobuf:"varint,1,opt,name=expiry_unix,json=expiryUnix,proto3" json:"expiry_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertExpiryChange) Reset() {
	*x = CertExpiryChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertExpiryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertExpiryChange) ProtoMessage() {}

func (x *CertExpiryChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertExpiryChange.ProtoReflect.Descriptor instead.
func (*CertExpiryChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *CertExpiryChange) GetExpiryUnix() int64 {
	if x != nil {
		return x.ExpiryUnix
	}
	return 0
}

type DenyChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerPub       []byte                 `protobuf:"bytes,1,opt,name=peer_pub,json=peerPub,proto3" json:"peer_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyChange) Reset() {
	*x = DenyChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyChange) ProtoMessage() {}

func (x *DenyChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyChange.ProtoReflect.Descriptor instead.
func (*DenyChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *DenyChange) GetPeerPub() []byte {
	if x != nil {
		return x.PeerPub
	}
	return nil
}

type NatTypeChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NatType       uint32                 `protobuf:"varint,1,opt,name=nat_type,json=natType,proto3" json:"nat_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatTypeChange) Reset() {
	*x = NatTypeChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatTypeChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatTypeChange) ProtoMessage() {}

func (x *NatTypeChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatTypeChange.ProtoReflect.Descriptor instead.
func (*NatTypeChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{10}
}

func (x *NatTypeChange) GetNatType() uint32 {
	if x != nil {
		return x.NatType
	}
	return 0
}

type ResourceTelemetryChange struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       uint32                 `protobuf:"varint,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent       uint32                 `protobuf:"varint,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	MemTotalBytes    uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	NumCpu           uint32                 `protobuf:"varint,4,opt,name=num_cpu,json=numCpu,proto3" json:"num_cpu,omitempty"`
	CpuBudgetPercent uint32                 `protobuf:"varint,5,opt,name=cpu_budget_percent,json=cpuBudgetPercent,proto3" json:"cpu_budget_percent,omitempty"`
	MemBudgetPercent uint32                 `protobuf:"varint,6,opt,name=mem_budget_percent,json=memBudgetPercent,proto3" json:"mem_budget_percent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceTelemetryChange) Reset() {
	*x = ResourceTelemetryChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceTelemetryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceTelemetryChange) ProtoMessage() {}

func (x *ResourceTelemetryChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceTelemetryChange.ProtoReflect.Descriptor instead.
func (*ResourceTelemetryChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *ResourceTelemetryChange) GetCpuPercent() uint32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceTelemetryChange) GetMemPercent() uint32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ResourceTelemetryChange) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *ResourceTelemetryChange) GetNumCpu() uint32 {
	if x != nil {
		return x.NumCpu
	}
	return 0
}

func (x *ResourceTelemetryChange) GetCpuBudgetPercent() uint32 {
	if x != nil {
		return x.CpuBudgetPercent
	}
	return 0
}

func (x *ResourceTelemetryChange) GetMemBudgetPercent() uint32 {
	if x != nil {
		return x.MemBudgetPercent
	}
	return 0
}

type WorkloadSpecChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	MinReplicas   uint32                 `protobuf:"varint,2,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MemoryPages   uint32                 `protobuf:"varint,3,opt,name=memory_pages,json=memoryPages,proto3" json:"memory_pages,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Spread        float32                `protobuf:"fixed32,6,opt,name=spread,proto3" json:"spread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpecChange) Reset() {
	*x = WorkloadSpecChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpecChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpecChange) ProtoMessage() {}

func (x *WorkloadSpecChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpecChange.ProtoReflect.Descriptor instead.
func (*WorkloadSpecChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{12}
}

func (x *WorkloadSpecChange) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *WorkloadSpecChange) GetMinReplicas() uint32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *WorkloadSpecChange) GetMemoryPages() uint32 {
	if x != nil {
		return x.MemoryPages
	}
	return 0
}

func (x *WorkloadSpecChange) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *WorkloadSpecChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadSpecChange) GetSpread() float32 {
	if x != nil {
		return x.Spread
	}
	return 0
}

type SeedLoadChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         map[string]float32     `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedLoadChange) Reset() {
	*x = SeedLoadChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedLoadChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedLoadChange) ProtoMessage() {}

func (x *SeedLoadChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedLoadChange.ProtoReflect.Descriptor instead.
func (*SeedLoadChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{13}
}

func (x *SeedLoadChange) GetRates() map[string]float32 {
	if x != nil {
		return x.Rates
	}
	return nil
}

type SeedDemandChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         map[string]float32     `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedDemandChange) Reset() {
	*x = SeedDemandChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedDemandChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedDemandChange) ProtoMessage() {}

func (x *SeedDemandChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedDemandChange.ProtoReflect.Descriptor instead.
func (*SeedDemandChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{14}
}

func (x *SeedDemandChange) GetRates() map[string]float32 {
	if x != nil {
		return x.Rates
	}
	return nil
}

type WorkloadClaimChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadClaimChange) Reset() {
	*x = WorkloadClaimChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadClaimChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadClaimChange) ProtoMessage() {}

func (x *WorkloadClaimChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadClaimChange.ProtoReflect.Descriptor instead.
func (*WorkloadClaimChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{15}
}

func (x *WorkloadClaimChange) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TrafficRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	BytesIn       uint64                 `protobuf:"varint,2,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut      uint64                 `protobuf:"varint,3,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRate) Reset() {
	*x = TrafficRate{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRate) ProtoMessage() {}

func (x *TrafficRate) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRate.ProtoReflect.Descriptor instead.
func (*TrafficRate) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{16}
}

func (x *TrafficRate) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *TrafficRate) GetBytesIn() uint64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *TrafficRate) GetBytesOut() uint64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

type TrafficHeatmapChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*TrafficRate         `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficHeatmapChange) Reset() {
	*x = TrafficHeatmapChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficHeatmapChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficHeatmapChange) ProtoMessage() {}

func (x *TrafficHeatmapChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficHeatmapChange.ProtoReflect.Descriptor instead.
func (*TrafficHeatmapChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{17}
}

func (x *TrafficHeatmapChange) GetRates() []*TrafficRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type HeartbeatChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatChange) Reset() {
	*x = HeartbeatChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatChange) ProtoMessage() {}

func (x *HeartbeatChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatChange.ProtoReflect.Descriptor instead.
func (*HeartbeatChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{18}
}

type AdminCapableChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminCapableChange) Reset() {
	*x = AdminCapableChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminCapableChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCapableChange) ProtoMessage() {}

func (x *AdminCapableChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCapableChange.ProtoReflect.Descriptor instead.
func (*AdminCapableChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{19}
}

type NodeNameChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeNameChange) Reset() {
	*x = NodeNameChange{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeNameChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeNameChange) ProtoMessage() {}

func (x *NodeNameChange) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeNameChange.ProtoReflect.Descriptor instead.
func (*NodeNameChange) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{20}
}

func (x *NodeNameChange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GossipEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	PeerId  string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Counter uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	// Types that are valid to be assigned to Change:
	//
	//	*GossipEvent_Network
	//	*GossipEvent_ObservedAddress
	//	*GossipEvent_CertExpiry
	//	*GossipEvent_Service
	//	*GossipEvent_Reachability
	//	*GossipEvent_PubliclyAccessible
	//	*GossipEvent_Vivaldi
	//	*GossipEvent_NatType
	//	*GossipEvent_ResourceTelemetry
	//	*GossipEvent_Deny
	//	*GossipEvent_WorkloadSpec
	//	*GossipEvent_WorkloadClaim
	//	*GossipEvent_TrafficHeatmap
	//	*GossipEvent_Heartbeat
	//	*GossipEvent_SeedLoad
	//	*GossipEvent_AdminCapable
	//	*GossipEvent_NodeName
	//	*GossipEvent_SeedDemand
	Change        isGossipEvent_Change `protobuf_oneof:"change"`
	Deleted       bool                 `protobuf:"varint,14,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEvent) Reset() {
	*x = GossipEvent{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEvent) ProtoMessage() {}

func (x *GossipEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEvent.ProtoReflect.Descriptor instead.
func (*GossipEvent) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{21}
}

func (x *GossipEvent) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GossipEvent) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *GossipEvent) GetChange() isGossipEvent_Change {
	if x != nil {
		return x.Change
	}
	return nil
}

func (x *GossipEvent) GetNetwork() *NetworkChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *GossipEvent) GetObservedAddress() *ObservedAddressChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_ObservedAddress); ok {
			return x.ObservedAddress
		}
	}
	return nil
}

func (x *GossipEvent) GetCertExpiry() *CertExpiryChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_CertExpiry); ok {
			return x.CertExpiry
		}
	}
	return nil
}

func (x *GossipEvent) GetService() *ServiceChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_Service); ok {
			return x.Service
		}
	}
	return nil
}

func (x *GossipEvent) GetReachability() *ReachabilityChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_Reachability); ok {
			return x.Reachability
		}
	}
	return nil
}

func (x *GossipEvent) GetPubliclyAccessible() *PubliclyAccessibleChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_PubliclyAccessible); ok {
			return x.PubliclyAccessible
		}
	}
	return nil
}

func (x *GossipEvent) GetVivaldi() *VivaldiCoordinateChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_Vivaldi); ok {
			return x.Vivaldi
		}
	}
	return nil
}

func (x *GossipEvent) GetNatType() *NatTypeChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_NatType); ok {
			return x.NatType
		}
	}
	return nil
}

func (x *GossipEvent) GetResourceTelemetry() *ResourceTelemetryChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_ResourceTelemetry); ok {
			return x.ResourceTelemetry
		}
	}
	return nil
}

func (x *GossipEvent) GetDeny() *DenyChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_Deny); ok {
			return x.Deny
		}
	}
	return nil
}

func (x *GossipEvent) GetWorkloadSpec() *WorkloadSpecChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_WorkloadSpec); ok {
			return x.WorkloadSpec
		}
	}
	return nil
}

func (x *GossipEvent) GetWorkloadClaim() *WorkloadClaimChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_WorkloadClaim); ok {
			return x.WorkloadClaim
		}
	}
	return nil
}

func (x *GossipEvent) GetTrafficHeatmap() *TrafficHeatmapChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_TrafficHeatmap); ok {
			return x.TrafficHeatmap
		}
	}
	return nil
}

func (x *GossipEvent) GetHeartbeat() *HeartbeatChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *GossipEvent) GetSeedLoad() *SeedLoadChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_SeedLoad); ok {
			return x.SeedLoad
		}
	}
	return nil
}

func (x *GossipEvent) GetAdminCapable() *AdminCapableChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_AdminCapable); ok {
			return x.AdminCapable
		}
	}
	return nil
}

func (x *GossipEvent) GetNodeName() *NodeNameChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_NodeName); ok {
			return x.NodeName
		}
	}
	return nil
}

func (x *GossipEvent) GetSeedDemand() *SeedDemandChange {
	if x != nil {
		if x, ok := x.Change.(*GossipEvent_SeedDemand); ok {
			return x.SeedDemand
		}
	}
	return nil
}

func (x *GossipEvent) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type isGossipEvent_Change interface {
	isGossipEvent_Change()
}

type GossipEvent_Network struct {
	Network *NetworkChange `protobuf:"bytes,3,opt,name=network,proto3,oneof"`
}

type GossipEvent_ObservedAddress struct {
	ObservedAddress *ObservedAddressChange `protobuf:"bytes,4,opt,name=observed_address,json=observedAddress,proto3,oneof"`
}

type GossipEvent_CertExpiry struct {
	CertExpiry *CertExpiryChange `protobuf:"bytes,5,opt,name=cert_expiry,json=certExpiry,proto3,oneof"`
}

type GossipEvent_Service struct {
	Service *ServiceChange `protobuf:"bytes,6,opt,name=service,proto3,oneof"`
}

type GossipEvent_Reachability struct {
	Reachability *ReachabilityChange `protobuf:"bytes,7,opt,name=reachability,proto3,oneof"`
}

type GossipEvent_PubliclyAccessible struct {
	PubliclyAccessible *PubliclyAccessibleChange `protobuf:"bytes,9,opt,name=publicly_accessible,json=publiclyAccessible,proto3,oneof"`
}

type GossipEvent_Vivaldi struct {
	Vivaldi *VivaldiCoordinateChange `protobuf:"bytes,10,opt,name=vivaldi,proto3,oneof"`
}

type GossipEvent_NatType struct {
	NatType *NatTypeChange `protobuf:"bytes,11,opt,name=nat_type,json=natType,proto3,oneof"`
}

type GossipEvent_ResourceTelemetry struct {
	ResourceTelemetry *ResourceTelemetryChange `protobuf:"bytes,12,opt,name=resource_telemetry,json=resourceTelemetry,proto3,oneof"`
}

type GossipEvent_Deny struct {
	Deny *DenyChange `protobuf:"bytes,13,opt,name=deny,proto3,oneof"`
}

type GossipEvent_WorkloadSpec struct {
	WorkloadSpec *WorkloadSpecChange `protobuf:"bytes,15,opt,name=workload_spec,json=workloadSpec,proto3,oneof"`
}

type GossipEvent_WorkloadClaim struct {
	WorkloadClaim *WorkloadClaimChange `protobuf:"bytes,16,opt,name=workload_claim,json=workloadClaim,proto3,oneof"`
}

type GossipEvent_TrafficHeatmap struct {
	TrafficHeatmap *TrafficHeatmapChange `protobuf:"bytes,17,opt,name=traffic_heatmap,json=trafficHeatmap,proto3,oneof"`
}

type GossipEvent_Heartbeat struct {
	Heartbeat *HeartbeatChange `protobuf:"bytes,18,opt,name=heartbeat,proto3,oneof"`
}

type GossipEvent_SeedLoad struct {
	SeedLoad *SeedLoadChange `protobuf:"bytes,19,opt,name=seed_load,json=seedLoad,proto3,oneof"`
}

type GossipEvent_AdminCapable struct {
	AdminCapable *AdminCapableChange `protobuf:"bytes,20,opt,name=admin_capable,json=adminCapable,proto3,oneof"`
}

type GossipEvent_NodeName struct {
	NodeName *NodeNameChange `protobuf:"bytes,21,opt,name=node_name,json=nodeName,proto3,oneof"`
}

type GossipEvent_SeedDemand struct {
	SeedDemand *SeedDemandChange `protobuf:"bytes,22,opt,name=seed_demand,json=seedDemand,proto3,oneof"`
}

func (*GossipEvent_Network) isGossipEvent_Change() {}

func (*GossipEvent_ObservedAddress) isGossipEvent_Change() {}

func (*GossipEvent_CertExpiry) isGossipEvent_Change() {}

func (*GossipEvent_Service) isGossipEvent_Change() {}

func (*GossipEvent_Reachability) isGossipEvent_Change() {}

func (*GossipEvent_PubliclyAccessible) isGossipEvent_Change() {}

func (*GossipEvent_Vivaldi) isGossipEvent_Change() {}

func (*GossipEvent_NatType) isGossipEvent_Change() {}

func (*GossipEvent_ResourceTelemetry) isGossipEvent_Change() {}

func (*GossipEvent_Deny) isGossipEvent_Change() {}

func (*GossipEvent_WorkloadSpec) isGossipEvent_Change() {}

func (*GossipEvent_WorkloadClaim) isGossipEvent_Change() {}

func (*GossipEvent_TrafficHeatmap) isGossipEvent_Change() {}

func (*GossipEvent_Heartbeat) isGossipEvent_Change() {}

func (*GossipEvent_SeedLoad) isGossipEvent_Change() {}

func (*GossipEvent_AdminCapable) isGossipEvent_Change() {}

func (*GossipEvent_NodeName) isGossipEvent_Change() {}

func (*GossipEvent_SeedDemand) isGossipEvent_Change() {}

type GossipEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GossipEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEventBatch) Reset() {
	*x = GossipEventBatch{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEventBatch) ProtoMessage() {}

func (x *GossipEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEventBatch.ProtoReflect.Descriptor instead.
func (*GossipEventBatch) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{22}
}

func (x *GossipEventBatch) GetEvents() []*GossipEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// RuntimeState is the on-disk format for daemon-managed runtime state (state.pb).
type RuntimeState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Peers           []*PeerState           `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	ConsumedInvites []*ConsumedInvite      `protobuf:"bytes,2,rep,name=consumed_invites,json=consumedInvites,proto3" json:"consumed_invites,omitempty"`
	DeniedPeers     [][]byte               `protobuf:"bytes,3,rep,name=denied_peers,json=deniedPeers,proto3" json:"denied_peers,omitempty"`
	WorkloadSpecs   []*WorkloadSpecChange  `protobuf:"bytes,4,rep,name=workload_specs,json=workloadSpecs,proto3" json:"workload_specs,omitempty"`
	GossipState     []byte                 `protobuf:"bytes,5,opt,name=gossip_state,json=gossipState,proto3" json:"gossip_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeState) Reset() {
	*x = RuntimeState{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeState) ProtoMessage() {}

func (x *RuntimeState) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeState.ProtoReflect.Descriptor instead.
func (*RuntimeState) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{23}
}

func (x *RuntimeState) GetPeers() []*PeerState {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RuntimeState) GetConsumedInvites() []*ConsumedInvite {
	if x != nil {
		return x.ConsumedInvites
	}
	return nil
}

func (x *RuntimeState) GetDeniedPeers() [][]byte {
	if x != nil {
		return x.DeniedPeers
	}
	return nil
}

func (x *RuntimeState) GetWorkloadSpecs() []*WorkloadSpecChange {
	if x != nil {
		return x.WorkloadSpecs
	}
	return nil
}

func (x *RuntimeState) GetGossipState() []byte {
	if x != nil {
		return x.GossipState
	}
	return nil
}

type PeerState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeerPub            []byte                 `protobuf:"bytes,1,opt,name=peer_pub,json=peerPub,proto3" json:"peer_pub,omitempty"`
	Addresses          []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Port               uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ExternalPort       uint32                 `protobuf:"varint,4,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	LastAddr           string                 `protobuf:"bytes,5,opt,name=last_addr,json=lastAddr,proto3" json:"last_addr,omitempty"`
	ExternalIp         string                 `protobuf:"bytes,6,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	PubliclyAccessible bool                   `protobuf:"varint,7,opt,name=publicly_accessible,json=publiclyAccessible,proto3" json:"publicly_accessible,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PeerState) Reset() {
	*x = PeerState{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerState) ProtoMessage() {}

func (x *PeerState) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerState.ProtoReflect.Descriptor instead.
func (*PeerState) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{24}
}

func (x *PeerState) GetPeerPub() []byte {
	if x != nil {
		return x.PeerPub
	}
	return nil
}

func (x *PeerState) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PeerState) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PeerState) GetExternalPort() uint32 {
	if x != nil {
		return x.ExternalPort
	}
	return 0
}

func (x *PeerState) GetLastAddr() string {
	if x != nil {
		return x.LastAddr
	}
	return ""
}

func (x *PeerState) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *PeerState) GetPubliclyAccessible() bool {
	if x != nil {
		return x.PubliclyAccessible
	}
	return false
}

type ConsumedInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ExpiryUnix    int64                  `protobuf:"varint,2,opt,name=expiry_unix,json=expiryUnix,proto3" json:"expiry_unix,omitempty"`
	ConsumedUnix  int64                  `protobuf:"varint,3,opt,name=consumed_unix,json=consumedUnix,proto3" json:"consumed_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumedInvite) Reset() {
	*x = ConsumedInvite{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumedInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumedInvite) ProtoMessage() {}

func (x *ConsumedInvite) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumedInvite.ProtoReflect.Descriptor instead.
func (*ConsumedInvite) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{25}
}

func (x *ConsumedInvite) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ConsumedInvite) GetExpiryUnix() int64 {
	if x != nil {
		return x.ExpiryUnix
	}
	return 0
}

func (x *ConsumedInvite) GetConsumedUnix() int64 {
	if x != nil {
		return x.ConsumedUnix
	}
	return 0
}

var File_pollen_state_v1_state_proto protoreflect.FileDescriptor

const file_pollen_state_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1bpollen/state/v1/state.proto\x12\x0fpollen.state.v1\x1a\x1bbuf/validate/validate.proto\"L\n" +
	"\n" +
	"PeerDigest\x12\x1f\n" +
	"\vmax_counter\x18\x01 \x01(\x04R\n" +
	"maxCounter\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x02 \x01(\x06R\tstateHash\"\x99\x01\n" +
	"\x06Digest\x128\n" +
	"\x05peers\x18\x01 \x03(\v2\".pollen.state.v1.Digest.PeersEntryR\x05peers\x1aU\n" +
	"\n" +
	"PeersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.pollen.state.v1.PeerDigestR\x05value:\x028\x01\"u\n" +
	"\rServiceChange\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12<\n" +
	"\bprotocol\x18\x03 \x01(\x0e2 .pollen.state.v1.ServiceProtocolR\bprotocol\"J\n" +
	"\x12ReachabilityChange\x124\n" +
	"\apeer_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x162\x11^[a-fA-F0-9]{64}$\x98\x01@R\x06peerId\"@\n" +
	"\rNetworkChange\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\rR\tlocalPort\";\n" +
	"\x15ObservedAddressChange\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\x1a\n" +
	"\x18PubliclyAccessibleChange\"c\n" +
	"\x17VivaldiCoordinateChange\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height\x12\x14\n" +
	"\x05error\x18\x04 \x01(\x01R\x05error\"3\n" +
	"\x10CertExpiryChange\x12\x1f\n" +
	"\vexpiry_unix\x18\x01 \x01(\x03R\n" +
	"expiryUnix\"0\n" +
	"\n" +
	"DenyChange\x12\"\n" +
	"\bpeer_pub\x18\x01 \x01(\fB\a\xbaH\x04z\x02h R\apeerPub\"*\n" +
	"\rNatTypeChange\x12\x19\n" +
	"\bnat_type\x18\x01 \x01(\rR\anatType\"\xf8\x01\n" +
	"\x17ResourceTelemetryChange\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\rR\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\rR\n" +
	"memPercent\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x04R\rmemTotalBytes\x12\x17\n" +
	"\anum_cpu\x18\x04 \x01(\rR\x06numCpu\x12,\n" +
	"\x12cpu_budget_percent\x18\x05 \x01(\rR\x10cpuBudgetPercent\x12,\n" +
	"\x12mem_budget_percent\x18\x06 \x01(\rR\x10memBudgetPercent\"\xb9\x01\n" +
	"\x12WorkloadSpecChange\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12!\n" +
	"\fmin_replicas\x18\x02 \x01(\rR\vminReplicas\x12!\n" +
	"\fmemory_pages\x18\x03 \x01(\rR\vmemoryPages\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\rR\ttimeoutMs\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06spread\x18\x06 \x01(\x02R\x06spread\"\x8c\x01\n" +
	"\x0eSeedLoadChange\x12@\n" +
	"\x05rates\x18\x01 \x03(\v2*.pollen.state.v1.SeedLoadChange.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x90\x01\n" +
	"\x10SeedDemandChange\x12B\n" +
	"\x05rates\x18\x01 \x03(\v2,.pollen.state.v1.SeedDemandChange.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\")\n" +
	"\x13WorkloadClaimChange\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"{\n" +
	"\vTrafficRate\x124\n" +
	"\apeer_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x162\x11^[a-fA-F0-9]{64}$\x98\x01@R\x06peerId\x12\x19\n" +
	"\bbytes_in\x18\x02 \x01(\x04R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x03 \x01(\x04R\bbytesOut\"J\n" +
	"\x14TrafficHeatmapChange\x122\n" +
	"\x05rates\x18\x01 \x03(\v2\x1c.pollen.state.v1.TrafficRateR\x05rates\"\x11\n" +
	"\x0fHeartbeatChange\"\x14\n" +
	"\x12AdminCapableChange\"B\n" +
	"\x0eNodeNameChange\x120\n" +
	"\x04name\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18@2\x11^[a-zA-Z0-9._-]+$R\x04name\"\x8f\v\n" +
	"\vGossipEvent\x124\n" +
	"\apeer_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x162\x11^[a-fA-F0-9]{64}$\x98\x01@R\x06peerId\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\x12:\n" +
	"\anetwork\x18\x03 \x01(\v2\x1e.pollen.state.v1.NetworkChangeH\x00R\anetwork\x12S\n" +
	"\x10observed_address\x18\x04 \x01(\v2&.pollen.state.v1.ObservedAddressChangeH\x00R\x0fobservedAddress\x12D\n" +
	"\vcert_expiry\x18\x05 \x01(\v2!.pollen.state.v1.CertExpiryChangeH\x00R\n" +
	"certExpiry\x12:\n" +
	"\aservice\x18\x06 \x01(\v2\x1e.pollen.state.v1.ServiceChangeH\x00R\aservice\x12I\n" +
	"\freachability\x18\a \x01(\v2#.pollen.state.v1.ReachabilityChangeH\x00R\freachability\x12\\\n" +
	"\x13publicly_accessible\x18\t \x01(\v2).pollen.state.v1.PubliclyAccessibleChangeH\x00R\x12publiclyAccessible\x12D\n" +
	"\avivaldi\x18\n" +
	" \x01(\v2(.pollen.state.v1.VivaldiCoordinateChangeH\x00R\avivaldi\x12;\n" +
	"\bnat_type\x18\v \x01(\v2\x1e.pollen.state.v1.NatTypeChangeH\x00R\anatType\x12Y\n" +
	"\x12resource_telemetry\x18\f \x01(\v2(.pollen.state.v1.ResourceTelemetryChangeH\x00R\x11resourceTelemetry\x121\n" +
	"\x04deny\x18\r \x01(\v2\x1b.pollen.state.v1.DenyChangeH\x00R\x04deny\x12J\n" +
	"\rworkload_spec\x18\x0f \x01(\v2#.pollen.state.v1.WorkloadSpecChangeH\x00R\fworkloadSpec\x12M\n" +
	"\x0eworkload_claim\x18\x10 \x01(\v2$.pollen.state.v1.WorkloadClaimChangeH\x00R\rworkloadClaim\x12P\n" +
	"\x0ftraffic_heatmap\x18\x11 \x01(\v2%.pollen.state.v1.TrafficHeatmapChangeH\x00R\x0etrafficHeatmap\x12@\n" +
	"\theartbeat\x18\x12 \x01(\v2 .pollen.state.v1.HeartbeatChangeH\x00R\theartbeat\x12>\n" +
	"\tseed_load\x18\x13 \x01(\v2\x1f.pollen.state.v1.SeedLoadChangeH\x00R\bseedLoad\x12J\n" +
	"\radmin_capable\x18\x14 \x01(\v2#.pollen.state.v1.AdminCapableChangeH\x00R\fadminCapable\x12>\n" +
	"\tnode_name\x18\x15 \x01(\v2\x1f.pollen.state.v1.NodeNameChangeH\x00R\bnodeName\x12D\n" +
	"\vseed_demand\x18\x16 \x01(\v2!.pollen.state.v1.SeedDemandChangeH\x00R\n" +
	"seedDemand\x12\x18\n" +
	"\adeleted\x18\x0e \x01(\bR\adeletedB\b\n" +
	"\x06change\"H\n" +
	"\x10GossipEventBatch\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.pollen.state.v1.GossipEventR\x06events\"\x9e\x02\n" +
	"\fRuntimeState\x120\n" +
	"\x05peers\x18\x01 \x03(\v2\x1a.pollen.state.v1.PeerStateR\x05peers\x12J\n" +
	"\x10consumed_invites\x18\x02 \x03(\v2\x1f.pollen.state.v1.ConsumedInviteR\x0fconsumedInvites\x12!\n" +
	"\fdenied_peers\x18\x03 \x03(\fR\vdeniedPeers\x12J\n" +
	"\x0eworkload_specs\x18\x04 \x03(\v2#.pollen.state.v1.WorkloadSpecChangeR\rworkloadSpecs\x12!\n" +
	"\fgossip_state\x18\x05 \x01(\fR\vgossipState\"\xec\x01\n" +
	"\tPeerState\x12\x19\n" +
	"\bpeer_pub\x18\x01 \x01(\fR\apeerPub\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12#\n" +
	"\rexternal_port\x18\x04 \x01(\rR\fexternalPort\x12\x1b\n" +
	"\tlast_addr\x18\x05 \x01(\tR\blastAddr\x12\x1f\n" +
	"\vexternal_ip\x18\x06 \x01(\tR\n" +
	"externalIp\x12/\n" +
	"\x13publicly_accessible\x18\a \x01(\bR\x12publiclyAccessible\"q\n" +
	"\x0eConsumedInvite\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x1f\n" +
	"\vexpiry_unix\x18\x02 \x01(\x03R\n" +
	"expiryUnix\x12#\n" +
	"\rconsumed_unix\x18\x03 \x01(\x03R\fconsumedUnix*g\n" +
	"\x0fServiceProtocol\x12 \n" +
	"\x1cSERVICE_PROTOCOL_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVICE_PROTOCOL_TCP\x10\x01\x12\x18\n" +
	"\x14SERVICE_PROTOCOL_UDP\x10\x02B@Z>github.com/sambigeara/pollen/api/genpb/pollen/state/v1;statev1b\x06proto3"

var (
	file_pollen_state_v1_state_proto_rawDescOnce sync.Once
	file_pollen_state_v1_state_proto_rawDescData []byte
)

func file_pollen_state_v1_state_proto_rawDescGZIP() []byte {
	file_pollen_state_v1_state_proto_rawDescOnce.Do(func() {
		file_pollen_state_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pollen_state_v1_state_proto_rawDesc), len(file_pollen_state_v1_state_proto_rawDesc)))
	})
	return file_pollen_state_v1_state_proto_rawDescData
}

var file_pollen_state_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pollen_state_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pollen_state_v1_state_proto_goTypes = []any{
	(ServiceProtocol)(0),             // 0: pollen.state.v1.ServiceProtocol
	(*PeerDigest)(nil),               // 1: pollen.state.v1.PeerDigest
	(*Digest)(nil),                   // 2: pollen.state.v1.Digest
	(*ServiceChange)(nil),            // 3: pollen.state.v1.ServiceChange
	(*ReachabilityChange)(nil),       // 4: pollen.state.v1.ReachabilityChange
	(*NetworkChange)(nil),            // 5: pollen.state.v1.NetworkChange
	(*ObservedAddressChange)(nil),    // 6: pollen.state.v1.ObservedAddressChange
	(*PubliclyAccessibleChange)(nil), // 7: pollen.state.v1.PubliclyAccessibleChange
	(*VivaldiCoordinateChange)(nil),  // 8: pollen.state.v1.VivaldiCoordinateChange
	(*CertExpiryChange)(nil),         // 9: pollen.state.v1.CertExpiryChange
	(*DenyChange)(nil),               // 10: pollen.state.v1.DenyChange
	(*NatTypeChange)(nil),            // 11: pollen.state.v1.NatTypeChange
	(*ResourceTelemetryChange)(nil),  // 12: pollen.state.v1.ResourceTelemetryChange
	(*WorkloadSpecChange)(nil),       // 13: pollen.state.v1.WorkloadSpecChange
	(*SeedLoadChange)(nil),           // 14: pollen.state.v1.SeedLoadChange
	(*SeedDemandChange)(nil),         // 15: pollen.state.v1.SeedDemandChange
	(*WorkloadClaimChange)(nil),      // 16: pollen.state.v1.WorkloadClaimChange
	(*TrafficRate)(nil),              // 17: pollen.state.v1.TrafficRate
	(*TrafficHeatmapChange)(nil),     // 18: pollen.state.v1.TrafficHeatmapChange
	(*HeartbeatChange)(nil),          // 19: pollen.state.v1.HeartbeatChange
	(*AdminCapableChange)(nil),       // 20: pollen.state.v1.AdminCapableChange
	(*NodeNameChange)(nil),           // 21: pollen.state.v1.NodeNameChange
	(*GossipEvent)(nil),              // 22: pollen.state.v1.GossipEvent
	(*GossipEventBatch)(nil),         // 23: pollen.state.v1.GossipEventBatch
	(*RuntimeState)(nil),             // 24: pollen.state.v1.RuntimeState
	(*PeerState)(nil),                // 25: pollen.state.v1.PeerState
	(*ConsumedInvite)(nil),           // 26: pollen.state.v1.ConsumedInvite
	nil,                              // 27: pollen.state.v1.Digest.PeersEntry
	nil,                              // 28: pollen.state.v1.SeedLoadChange.RatesEntry
	nil,                              // 29: pollen.state.v1.SeedDemandChange.RatesEntry
}
var file_pollen_state_v1_state_proto_depIdxs = []int32{
	27, // 0: pollen.state.v1.Digest.peers:type_name -> pollen.state.v1.Digest.PeersEntry
	0,  // 1: pollen.state.v1.ServiceChange.protocol:type_name -> pollen.state.v1.ServiceProtocol
	28, // 2: pollen.state.v1.SeedLoadChange.rates:type_name -> pollen.state.v1.SeedLoadChange.RatesEntry
	29, // 3: pollen.state.v1.SeedDemandChange.rates:type_name -> pollen.state.v1.SeedDemandChange.RatesEntry
	17, // 4: pollen.state.v1.TrafficHeatmapChange.rates:type_name -> pollen.state.v1.TrafficRate
	5,  // 5: pollen.state.v1.GossipEvent.network:type_name -> pollen.state.v1.NetworkChange
	6,  // 6: pollen.state.v1.GossipEvent.observed_address:type_name -> pollen.state.v1.ObservedAddressChange
	9,  // 7: pollen.state.v1.GossipEvent.cert_expiry:type_name -> pollen.state.v1.CertExpiryChange
	3,  // 8: pollen.state.v1.GossipEvent.service:type_name -> pollen.state.v1.ServiceChange
	4,  // 9: pollen.state.v1.GossipEvent.reachability:type_name -> pollen.state.v1.ReachabilityChange
	7,  // 10: pollen.state.v1.GossipEvent.publicly_accessible:type_name -> pollen.state.v1.PubliclyAccessibleChange
	8,  // 11: pollen.state.v1.GossipEvent.vivaldi:type_name -> pollen.state.v1.VivaldiCoordinateChange
	11, // 12: pollen.state.v1.GossipEvent.nat_type:type_name -> pollen.state.v1.NatTypeChange
	12, // 13: pollen.state.v1.GossipEvent.resource_telemetry:type_name -> pollen.state.v1.ResourceTelemetryChange
	10, // 14: pollen.state.v1.GossipEvent.deny:type_name -> pollen.state.v1.DenyChange
	13, // 15: pollen.state.v1.GossipEvent.workload_spec:type_name -> pollen.state.v1.WorkloadSpecChange
	16, // 16: pollen.state.v1.GossipEvent.workload_claim:type_name -> pollen.state.v1.WorkloadClaimChange
	18, // 17: pollen.state.v1.GossipEvent.traffic_heatmap:type_name -> pollen.state.v1.TrafficHeatmapChange
	19, // 18: pollen.state.v1.GossipEvent.heartbeat:type_name -> pollen.state.v1.HeartbeatChange
	14, // 19: pollen.state.v1.GossipEvent.seed_load:type_name -> pollen.state.v1.SeedLoadChange
	20, // 20: pollen.state.v1.GossipEvent.admin_capable:type_name -> pollen.state.v1.AdminCapableChange
	21, // 21: pollen.state.v1.GossipEvent.node_name:type_name -> pollen.state.v1.NodeNameChange
	15, // 22: pollen.state.v1.GossipEvent.seed_demand:type_name -> pollen.state.v1.SeedDemandChange
	22, // 23: pollen.state.v1.GossipEventBatch.events:type_name -> pollen.state.v1.GossipEvent
	25, // 24: pollen.state.v1.RuntimeState.peers:type_name -> pollen.state.v1.PeerState
	26, // 25: pollen.state.v1.RuntimeState.consumed_invites:type_name -> pollen.state.v1.ConsumedInvite
	13, // 26: pollen.state.v1.RuntimeState.workload_specs:type_name -> pollen.state.v1.WorkloadSpecChange
	1,  // 27: pollen.state.v1.Digest.PeersEntry.value:type_name -> pollen.state.v1.PeerDigest
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_pollen_state_v1_state_proto_init() }
func file_pollen_state_v1_state_proto_init() {
	if File_pollen_state_v1_state_proto != nil {
		return
	}
	file_pollen_state_v1_state_proto_msgTypes[21].OneofWrappers = []any{
		(*GossipEvent_Network)(nil),
		(*GossipEvent_ObservedAddress)(nil),
		(*GossipEvent_CertExpiry)(nil),
		(*GossipEvent_Service)(nil),
		(*GossipEvent_Reachability)(nil),
		(*GossipEvent_PubliclyAccessible)(nil),
		(*GossipEvent_Vivaldi)(nil),
		(*GossipEvent_NatType)(nil),
		(*GossipEvent_ResourceTelemetry)(nil),
		(*GossipEvent_Deny)(nil),
		(*GossipEvent_WorkloadSpec)(nil),
		(*GossipEvent_WorkloadClaim)(nil),
		(*GossipEvent_TrafficHeatmap)(nil),
		(*GossipEvent_Heartbeat)(nil),
		(*GossipEvent_SeedLoad)(nil),
		(*GossipEvent_AdminCapable)(nil),
		(*GossipEvent_NodeName)(nil),
		(*GossipEvent_SeedDemand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pollen_state_v1_state_proto_rawDesc), len(file_pollen_state_v1_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pollen_state_v1_state_proto_goTypes,
		DependencyIndexes: file_pollen_state_v1_state_proto_depIdxs,
		EnumInfos:         file_pollen_state_v1_state_proto_enumTypes,
		MessageInfos:      file_pollen_state_v1_state_proto_msgTypes,
	}.Build()
	File_pollen_state_v1_state_proto = out.File
	file_pollen_state_v1_state_proto_goTypes = nil
	file_pollen_state_v1_state_proto_depIdxs = nil
}
