// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pollen/state/v1/state.proto

package statev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Keys          *Keys                  `protobuf:"bytes,4,opt,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Node) GetKeys() *Keys {
	if x != nil {
		return x.Keys
	}
	return nil
}

type Keys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoisePub      []byte                 `protobuf:"bytes,1,opt,name=noise_pub,json=noisePub,proto3" json:"noise_pub,omitempty"`
	IdentityPub   []byte                 `protobuf:"bytes,2,opt,name=identity_pub,json=identityPub,proto3" json:"identity_pub,omitempty"`
	AdminPub      []byte                 `protobuf:"bytes,3,opt,name=admin_pub,json=adminPub,proto3,oneof" json:"admin_pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys) Reset() {
	*x = Keys{}
	mi := &file_pollen_state_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_pollen_state_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_pollen_state_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *Keys) GetNoisePub() []byte {
	if x != nil {
		return x.NoisePub
	}
	return nil
}

func (x *Keys) GetIdentityPub() []byte {
	if x != nil {
		return x.IdentityPub
	}
	return nil
}

func (x *Keys) GetAdminPub() []byte {
	if x != nil {
		return x.AdminPub
	}
	return nil
}

var File_pollen_state_v1_state_proto protoreflect.FileDescriptor

const file_pollen_state_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1bpollen/state/v1/state.proto\x12\x0fpollen.state.v1\x1a\x1bbuf/validate/validate.proto\"\x90\x01\n" +
	"\x04Node\x12+\n" +
	"\x02id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x162\x11^[a-fA-F0-9]{64}$\x98\x01@R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12)\n" +
	"\x04keys\x18\x04 \x01(\v2\x15.pollen.state.v1.KeysR\x04keys\"\x91\x01\n" +
	"\x04Keys\x12$\n" +
	"\tnoise_pub\x18\x01 \x01(\fB\a\xbaH\x04z\x02h R\bnoisePub\x12*\n" +
	"\fidentity_pub\x18\x02 \x01(\fB\a\xbaH\x04z\x02h R\videntityPub\x12)\n" +
	"\tadmin_pub\x18\x03 \x01(\fB\a\xbaH\x04z\x02h H\x00R\badminPub\x88\x01\x01B\f\n" +
	"\n" +
	"_admin_pubB@Z>github.com/sambigeara/pollen/api/genpb/pollen/state/v1;statev1b\x06proto3"

var (
	file_pollen_state_v1_state_proto_rawDescOnce sync.Once
	file_pollen_state_v1_state_proto_rawDescData []byte
)

func file_pollen_state_v1_state_proto_rawDescGZIP() []byte {
	file_pollen_state_v1_state_proto_rawDescOnce.Do(func() {
		file_pollen_state_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pollen_state_v1_state_proto_rawDesc), len(file_pollen_state_v1_state_proto_rawDesc)))
	})
	return file_pollen_state_v1_state_proto_rawDescData
}

var file_pollen_state_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pollen_state_v1_state_proto_goTypes = []any{
	(*Node)(nil), // 0: pollen.state.v1.Node
	(*Keys)(nil), // 1: pollen.state.v1.Keys
}
var file_pollen_state_v1_state_proto_depIdxs = []int32{
	1, // 0: pollen.state.v1.Node.keys:type_name -> pollen.state.v1.Keys
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pollen_state_v1_state_proto_init() }
func file_pollen_state_v1_state_proto_init() {
	if File_pollen_state_v1_state_proto != nil {
		return
	}
	file_pollen_state_v1_state_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pollen_state_v1_state_proto_rawDesc), len(file_pollen_state_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pollen_state_v1_state_proto_goTypes,
		DependencyIndexes: file_pollen_state_v1_state_proto_depIdxs,
		MessageInfos:      file_pollen_state_v1_state_proto_msgTypes,
	}.Build()
	File_pollen_state_v1_state_proto = out.File
	file_pollen_state_v1_state_proto_goTypes = nil
	file_pollen_state_v1_state_proto_depIdxs = nil
}
